# -*- coding: utf-8 -*-
"""3.13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gJF-iVp7jQVYXbnvmWHs7Aif-AEJ3adb
"""

# Función para calcular el VPN
def calcular_vpn(flujos, tasa_descuento, inversion_inicial):
    vpn = -inversion_inicial
    for t, flujo in enumerate(flujos, start=1):
        vpn += flujo / (1 + tasa_descuento) ** t
    return vpn

# Solicitar datos al usuario
inversion_inicial = float(input("Ingresa el costo inicial de la inversión: "))

# Solicitar la tasa de descuento
tasa_descuento = float(input("Ingresa la tasa de descuento (por ejemplo, 0.08 para 8%): "))

# Solicitar los flujos de efectivo anuales
flujos = []
num_flujos = int(input("¿Cuántos flujos de efectivo tienes?: "))

for i in range(num_flujos):
    flujo = float(input(f"Ingrese el flujo de efectivo para el año {i + 1}: "))
    flujos.append(flujo)

# Cálculo del VPN
vpn = calcular_vpn(flujos, tasa_descuento, inversion_inicial)

# Mostrar el resultado
print(f"El Valor Presente Neto (VPN) es: {vpn:.2f}")